"""create chunks table

Revision ID: 72dcaf428a7f
Revises: b5657d4a7b59
Create Date: 2026-08-19 10:38:17.301683
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '72dcaf428a7f'
down_revision: str | None = 'b5657d4a7b59'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_documents_research_id', table_name='documents')
    op.drop_index('ix_documents_status', table_name='documents')
    op.drop_index('ix_researches_status', table_name='researches')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_researches_status', 'researches', ['status'], unique=False)
    op.create_index('ix_documents_status', 'documents', ['status'], unique=False)
    op.create_index('ix_documents_research_id', 'documents', ['research_id'], unique=False)
    # ### end Alembic commands ###
