"""add embeddings to chunks

Revision ID: 8acf69d2ca8e
Revises: 72dcaf428a7f
Create Date: 2026-08-19 10:47:03.738829
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '8acf69d2ca8e'
down_revision: str | None = '72dcaf428a7f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('embedding', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    op.add_column('chunks', sa.Column('embedding_model', sa.String(length=200), nullable=True))
    op.add_column('chunks', sa.Column('embedding_dimension', sa.Integer(), nullable=True))
    op.add_column('chunks', sa.Column('embedded_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chunks', 'embedded_at')
    op.drop_column('chunks', 'embedding_dimension')
    op.drop_column('chunks', 'embedding_model')
    op.drop_column('chunks', 'embedding')
    # ### end Alembic commands ###
