"""Add human_evaluations table

Revision ID: a01d7803a94d
Revises: 0005_workflow_checkpoints
Create Date: 2026-08-26 00:31:10.841086

Written by hand: the autogenerated revision also dropped dozens of unrelated
tables that share the database, so only the new table is created here.
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

revision: str = 'a01d7803a94d'
down_revision: str | None = '0005_workflow_checkpoints'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        'human_evaluations',
        sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
        sa.Column('claim_id', sa.UUID(), nullable=False),
        sa.Column('research_id', sa.UUID(), nullable=False),
        sa.Column('evaluator_id', sa.String(length=255), nullable=False),
        sa.Column('rating', sa.String(length=20), nullable=False),
        sa.Column('comment', sa.Text(), nullable=True),
        sa.Column('evaluated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_human_evaluations_claim_id'), 'human_evaluations', ['claim_id'], unique=False)
    op.create_index(op.f('ix_human_evaluations_research_id'), 'human_evaluations', ['research_id'], unique=False)


def downgrade() -> None:
    op.drop_index(op.f('ix_human_evaluations_research_id'), table_name='human_evaluations')
    op.drop_index(op.f('ix_human_evaluations_claim_id'), table_name='human_evaluations')
    op.drop_table('human_evaluations')
