"""add embeddings to chunks

Revision ID: c4544f4654ee
Revises: 8acf69d2ca8e
Create Date: 2026-08-19 11:05:39.434154
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'c4544f4654ee'
down_revision: str | None = '8acf69d2ca8e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
